### ISSUE TITLE
**CRASHING**:seccomp-bpf failure in syscall 0230

### ISSUE THREAD

**Issue by rodlessa** [futpib/pagraphcontrol#18] opened 2020-02-12 07:02 UTC
Not sure what happened, but after trying to launch it fails and only opens a dark window, after digging a little i've found out the this seems to be related with chromium so i tried to run with --no-sandbox which works.

Arch Linux 5.5.2 - Zen Kernel
Chromium 80.0.3987.100-1

**Comment by ChALkeR** [comment] 2020-02-22 22:32
This is caused by https://github.com/electron/electron/issues/22291 and caused by incompatibility between older Chromium/Electron and glibc >=2.31. Electron 8 is not affected, but this repo uses 6.
Backport PRs for Electron already exist (see the above link), but not landed yet.

**Comment by futpib** [comment] 2020-02-23 17:46
Fixed by 42c4c40d00846240671617e02e20e1574a5cbb5e

**Closed** 2020-02-23 17:47 UTC
